# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e6c95c94ae95b777ff075878aaba724ea0d447c7cd86d0cdfa314f1d2b754ec2b7b99324177650de541499b06dd62c85a490144d96689a13d06ebe0b1eec6c

test:
  secret_key_base: baaa70e08a61f23c0bbd2178f0ae603682bdc741c1e59e9262a9c4d55543de9b6df50eea3b2c82fc62818c6e3615a2933a6ab2a8bf8d0ba1f40f8db101f20232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
